apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp
  template:
    metadata:
      labels:
        app: smtp
    spec:
      containers:
        - name: smtp
          image: mailhog/mailhog
          ports:
            - containerPort: 1025   # SMTP port
            - containerPort: 8025   # HTTP UI port
---
apiVersion: v1
kind: Service
metadata:
  name: smtp-service
spec:
  type: NodePort
  selector:
    app: smtp
  ports:
    - protocol: TCP
      name: smtp
      port: 1025
      targetPort: 1025
      nodePort: 30004
    - protocol: TCP
      name: http
      port: 8025
      targetPort: 8025
      nodePort: 30005