[package]
name = "openai-poc"
version = "0.1.0"
edition = "2024"

[dependencies]
openai = { version = "1.1.0", default-features = false, features = ["rustls"] }
tokio = { version = "1", features = ["full"] }
