apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.14
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:4e545d890a83e4f438639bf72fe9a1f52fb48249ca1574ec3c68f713c9fab2ff
  hash-bionicgpt-rag-engine: sha256:c7d9506c7c178a78934b81c73d7fbb40a38ad8aabfff1cf62a84f7c3525b202c
  hash-bionicgpt-db-migrations: sha256:986868d0e03a08a616102e3d05243b095e2bf4e9d3b70e89d33fe915ce955ab6