apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.33
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:f09005cf3b57987e07b2bb29bb1ef930e4ced67509e273d764012f9c7a9b1609
  hash-bionicgpt-rag-engine: sha256:d984ac40c32bb1dcecb02afd0eba68fa79852d5551e9494be649d2b6eb5bb477
  hash-bionicgpt-db-migrations: sha256:6d4794dae9818ae74745d9e1a90e4ea35717590315c67fe89c4e23afe7a8aa38