apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.9
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:c8525dca47179965f4aa89b6fd67db4f259896af0baeb60af555e2f82d9bdf83
  hash-bionicgpt-rag-engine: sha256:a9483ceddcfdd3350eceb1ebe5ab3ada06336901539809742770a385a3b0365b
  hash-bionicgpt-db-migrations: sha256:05cc7a1f9974f5713406b4254d0f29944c7b86dcebff278fbb910a664a80fadf