apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.8.7
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:0b5b2efd92ddeb2376ea0c1e7f8afa5ced9a4e0c505602f28feda402d8070f84
  hash-bionicgpt-pipeline-job: sha256:097b55f3952d5582d136c15af4b30dd3bde59746b3bf320a3cd49a66c6f458a7
  hash-bionicgpt-db-migrations: sha256:90fa4445647eea8f33d8843c9a51767d6ecd03416efdb4dac5544217e420ebaa