apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.11.16
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:3a4b4082adfc32a7150fc144821842e3a149de7837df812dce5f5e13ab980e20
  hash-bionicgpt-rag-engine: sha256:bb3845715e51bfd902a8ad02e1ed4f789f10155ebacf0a8677a2af5fcfa24518
  hash-bionicgpt-db-migrations: sha256:921d057904e3d28680823f42ae40247716af76197310f7489892e4b86c87c6d5