apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.54
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:18e7cebfa369721fd80a66664edfc0d18836bc051c43cec4efd9aff7b03ca3d8
  hash-bionicgpt-rag-engine: sha256:b1d65133af6c942db2b148a8b153ec379cf772139c2a5be2f3eee3dbbee8a0dc
  hash-bionicgpt-db-migrations: sha256:be73f23b717b886866fbc17aceda87fe118bcea336481cd2f4231937b38568ba