apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.11.14
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:f2fd3174ff31fc37852b2a802c65fa6cdce4a5ab606ffca8cbc8672be039cd0c
  hash-bionicgpt-rag-engine: sha256:22954472944f233105a18949a2b16988c13eab32550544e83f4fc1bbc1e70eb0
  hash-bionicgpt-db-migrations: sha256:b85929e39ae4e5e436b5fe43318ad248263c4eb8ddf9b8f90720aff1608d127a