apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.11.18
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:ac866eb172c1811f78b3b9b81f89495b75056bc612ec4c0edc3a7aeaba1a1ee3
  hash-bionicgpt-rag-engine: sha256:268459331a84d2492600594bb3828a10d5f1d622d50d1599818baf4d11cc02ae
  hash-bionicgpt-db-migrations: sha256:adb2b4d936eedc69d951d8129f02bc144632673496489cfa37761ab443801c15