apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.37
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:8f8e2bc9133f32d791ccc67c533efece3b5ef68e03b50f5ace70f1d459375100
  hash-bionicgpt-rag-engine: sha256:7950d49ddf82766092ee41f0285854b0ec008368942a0eed2280efe2500952a5
  hash-bionicgpt-db-migrations: sha256:ae6a03526d41b2621232b107fff7cc18da0bcae282ac97045a61b31fd583f758