apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.11.23
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:a698f528a3a391a65af5b2bab49c34c2b6e9fcda07f658f1802d8c6570c236fe
  hash-bionicgpt-rag-engine: sha256:8138b9d6412eca253d3943bf01021e54b171f860a71829d24ba8cc70fa850816
  hash-bionicgpt-db-migrations: sha256:5b2819bf2bb749fc9b12dc25dc9acc0e04fd95bd66509895abd1b6b93ff3288d