apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.39
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:c9ce4f26d5d37d1905801c50e4fa1d374fea4b43bef70939d07f41434bb6a301
  hash-bionicgpt-rag-engine: sha256:9dda7a1b853c1e2d8a3d0247761cb40baf03db0c44cb7cd911a2fae9c586c52d
  hash-bionicgpt-db-migrations: sha256:e86c7b04db59c998ca8ddc822551e8d30257d9dfb69507c11ca205fba2a0c1d1