apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.18
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:c64b8bb4fe1c937f5e0364fe2234fb4755cb36626f80cb3434fee57f136646dc
  hash-bionicgpt-rag-engine: sha256:92998314ff9661851ed960b6c2b37f7203f70a319b9cbb96f88a6829bccb89e8
  hash-bionicgpt-db-migrations: sha256:b2969d137800fce6b649d464ee36249f0e603f6e1ef238b2cd48bf7f206964c3