apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.8.13
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:bbeef1f133e130b236090cce08b3f95cd1b2cededdd8311731de99430ff02c32
  hash-bionicgpt-pipeline-job: sha256:5b0cfaea2a780317e7e4d78e1227c1b51bb12d01cef93924cc87142417f4d252
  hash-bionicgpt-db-migrations: sha256:c0c850b52da64b8e125cfde69a1b70b1a7a75040806c2fe5bcbc171cd839d0bc