apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.11.6
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:b7280a68cfc864f6dfa22528b63cb9a3f4f8167600b1d40e0079f8043afa96e0
  hash-bionicgpt-rag-engine: sha256:516f4a7cd9ded672b6aa444fd7957e6c51c74993bd1b4b9159cb09355801e5fa
  hash-bionicgpt-db-migrations: sha256:1e3a483a4dfd5874a1d40106905ef5723e1413153899dd8e2b027eaea0a3835e