apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.7.37
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:c63416989cbfab8bc415b6655dac50b3f351dd0abfc5e3cdfc16793ba8f7979f
  hash-bionicgpt-pipeline-job: sha256:3bb256244da745b149fb6be6e7c17466f9349bc1acacf0229380b33ab4bf6217
  hash-bionicgpt-db-migrations: sha256:9328ced1615de9476a602514bae3eac9e9322c7229e80edd565d53a6b3553005