apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.19
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:4e1641dd68c083307273f1127abe03081021bcc203a1780d527220dd466a87f1
  hash-bionicgpt-rag-engine: sha256:fcd2b8d0a0cf7a96c25c92d510157863a5b53f6363f56bed478a820d3e35cb86
  hash-bionicgpt-db-migrations: sha256:c4acbc3172927fcb11427a4a9c2f941e52548a9d7b6bbe2126175467beff3dd6