apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.39
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:27baeeed0b000f98e32c053e2f7baa5394a0ddd5a29fdfb93639f87c5ae9dc2b
  hash-bionicgpt-rag-engine: sha256:e31d4f7ad49fa0dba5f87d4c1948f225127728740d5174aa545d8cd9a68175c0
  hash-bionicgpt-db-migrations: sha256:88366bd4f967d3b32ab1d2d9026ac1a40413106c1adab81e84e589349d74aeba