apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.29
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:c4e4ad0faf0d0f25f5d21d7b589699fec88ddbf24cc94a63a51b76336a435c75
  hash-bionicgpt-rag-engine: sha256:7e0c854c7205292d4e14600d6d897a306b6aa8c5b09bcb3e391984752a645625
  hash-bionicgpt-db-migrations: sha256:ccbab5281d57f27f2412e2733df2ad1824b1cd360c55b560fe5427a04df1b0f7