apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.8.6
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:560dd62cca402aef5761a05f1c4fc8922f66cd08e4c888e225dbcad72f5e6b6f
  hash-bionicgpt-pipeline-job: sha256:55d9cf15e546e8f305f489e9e4ac0e5240d5004c015c965f855297ee8f6091e4
  hash-bionicgpt-db-migrations: sha256:041666edb94ac98694d80cd1839c26a6b6eeeb961a9481832e961237e019bfd1