apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.18
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:bde113a320dce482e637d29957f693dbeeb616ced5f4fb4a337792ca226d7ba8
  hash-bionicgpt-rag-engine: sha256:447c7120182c1b32ca4d9b522d6a32eed15a4b726132d1059ea479413150a8a1
  hash-bionicgpt-db-migrations: sha256:826c21d59c52d944d2d86f3c9b6fc6e0e7e6ba1ec2aa43828c0ba7f40762e75b