apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.7.49
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:f010e096b4b241dd5297c89a7abd6be39eb5041fca91e70c953e606957ddb32a
  hash-bionicgpt-pipeline-job: sha256:e0729dedf1a1ba5a77a56ff6f1c3c49c1c940748a4ce27ccfb29f6795c321278
  hash-bionicgpt-db-migrations: sha256:bbcfe850d86c7ddc966d269a257a72a18e73ad4f823fdc872cbe38fdbf61e836