apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.1
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:53f707bdf093974665c8dd568df81f5b03b561d087e66a2f4f18b28d396a35b5
  hash-bionicgpt-rag-engine: sha256:75859c39485062a7ccbad10016e89c3959eee31df0d403a791fe2dde5b48df4e
  hash-bionicgpt-db-migrations: sha256:be9e7b0ad51b7d8f970507a475854c2757717154cc46d7754d6214d84d445790