apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.11
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:05ca6f61363d5f6bffe33b3eac668504a747f35d899c1e407989a697ed618cb4
  hash-bionicgpt-rag-engine: sha256:e22f8edc9548b60911da0d18f09e2666263709a346eb37afc86e6768d128655c
  hash-bionicgpt-db-migrations: sha256:9b3f1a422107dde88e195fa2c6915290edae732d9aabdbc1e333f4f0b6bfef73