apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.11.5
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:4cfa22d111942adf0c6a43dc929697f35ba71a1afa0b0038f5a5fe5c4d258071
  hash-bionicgpt-rag-engine: sha256:ffeaeb441258506040b51d064b2610a7071dbd49bba3cd0253245efcc5e0db34
  hash-bionicgpt-db-migrations: sha256:22968ec8aaa5191e7c94070b5d3b7b492eab9b19b8d47a256f58efb2c566d3e5