apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.8.5
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:7d30e28d30e7c6868d44e10f8ca4d8df79b0f607347415a73034dfd6c0aca7fd
  hash-bionicgpt-pipeline-job: sha256:6039a809ac151b124386e9b7a320b7b14918f458ffb8d4819671a3a78a4b7cf4
  hash-bionicgpt-db-migrations: sha256:5e3aee1776b1aa912210ee60b2e4f9d750396fea7b1322eac42d73be490588e1