apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.38
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:3428f464c2383a2824c091d2b96a4575489fff4fd8d6c15d4cb421d72f980d77
  hash-bionicgpt-rag-engine: sha256:54dc422069d7faa7acce7ffe06911394de920e5136f80a9326665bdd92dd219f
  hash-bionicgpt-db-migrations: sha256:b91db321d85a8c7621feb4ccb0cb18782ea26fdc31e8bf811fc30a6328a66ba1