apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.48
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:0c111014d0ad86138a8be8430013666c98c3c2f3a7bd11e75e6d6dd791f1a990
  hash-bionicgpt-rag-engine: sha256:7ac81a7785f989ae3d529ffb3450f1a72ccf4be8e7acb7205569c254383a192a
  hash-bionicgpt-db-migrations: sha256:0db6209e98b1e55a134bbe68eff306ff75293537d694acd2b9550862771f62d7