apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.0
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:cef596b533c61f79a26ce92dd53d37da1a324d7ce0196b576c04b93462c9557b
  hash-bionicgpt-rag-engine: sha256:a6fce7c93c202a1d6521b76d067bc2f6e887ccc5ca74031570429e8c84293f2d
  hash-bionicgpt-db-migrations: sha256:2805ba4c9f4f8e08506168b5c2ce740c5d64ead5b482b367cd2c087e4a17370e