apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.8.1
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:4df450afcae0263c7eb7f9fb1b3daeb088109bb3747b9cac70f4f9e1513d61f4
  hash-bionicgpt-pipeline-job: sha256:70cf2a2f98b97520c89847f755e138e437e7d0ad900353903c07bfd0f46e536a
  hash-bionicgpt-db-migrations: sha256:0cdbc13d1acf350a770064202c4932d52db88c11a4143cde949c00428ec8fdbe