apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.8.41
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:2304c421f6ffad11c1057a46241ce2a2edf7d28e04f66ba2fb85fa83467fb233
  hash-bionicgpt-rag-engine: sha256:867689cb1373f1559b412085658ac579c6c7a0494f779ee3048e82821954afb3
  hash-bionicgpt-db-migrations: sha256:8b12a13b1155ac2c97a81406198b8a998a22595f3b7e4fc0fb7b041247f33337