apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.8.24
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:ccb5f9d9b8c6b14d773ac416198f40f0a6b5a58dd0902f5ed26da1c4aa2cd31c
  hash-bionicgpt-rag-engine: sha256:c49e2ad73c722a71c9f987234e0a29bc2d6e17b7edc019a8a93ed8ad93461537
  hash-bionicgpt-db-migrations: sha256:ccca0c2a3e5846882c2da59502207aea59063bb0e50a363d0d9c9061dee2e799