apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.7.44
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:af74413e1e8f847e98c9301d65d590dbb563be631806cd7e854063a8260bba60
  hash-bionicgpt-pipeline-job: sha256:2f844e5a1d014de56b401985e01c4ef2daf29d4322d00c15fba974691c38d89f
  hash-bionicgpt-db-migrations: sha256:a2eec3a82b6692949c0ea93f088de17e1f74bff7e5e47cd919b139ed91aabc33