apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.38
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:373f8be227a1a46ed906e9db6239b289aaa7931d9eea42e5ad6697319c3b93d2
  hash-bionicgpt-rag-engine: sha256:e5a746ef149bbca5bfeabb2a73654c721df4847be631a889c7dcc2d038a46542
  hash-bionicgpt-db-migrations: sha256:a09f3aab3e00ee760b9221196ec8ad5b76d985178b4ef3faaaa699f2dc7c58da