apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.7.36
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:4a73d0988ef9c46d1a454df0eb31611c28a74e50ed9650000100abae3b357c61
  hash-bionicgpt-pipeline-job: sha256:e6f96728740c93d0392df59b0c5cd4cb3476410046df8bd8f0205d6a82575afc
  hash-bionicgpt-db-migrations: sha256:467a80e4b8c8ca96203d95553edd840ceda0995f1cb7d480a3c3f1d10052e901