apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.11.3
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:07e355b5d340d6b33daa1f672965cadb73272ba29ae67e7a6ccfca1bc7077055
  hash-bionicgpt-rag-engine: sha256:ce4c7ae45bd93b42a90cbfd77209811b83800ccbd33ce43782c17ab2c23fd781
  hash-bionicgpt-db-migrations: sha256:3c8d81c738b3fa6e004f11e2b9a934dc6f6453a0674dadea066f93764e04a38a