apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.8.40
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:285a2547b91d6a828c172996a43e77ae907da23c2ed3bf77f7a338e71a271398
  hash-bionicgpt-rag-engine: sha256:eb9cb30a946d108faf95791c52890669d11437effab134aa25ca58e1624b85aa
  hash-bionicgpt-db-migrations: sha256:0c2965bf82b810f9c3f8373ed02bed3fa9ba21a2475637c210e80977b91c7cfb