apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.25
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:5b081c85fe7c6eef221f44279becee457953eb1c6238eb79d580d8a085b70041
  hash-bionicgpt-rag-engine: sha256:16b01c8d526ed78d83117cd9d56af5a2586dbdbf3adc7194b3e569d8a1a3ed91
  hash-bionicgpt-db-migrations: sha256:7e53608e0c2d36100b702048c80cb1888b71b80cf1a7c353dec509257e0ac7b0