apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.41
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:b5b84b35a59f015003b4f88d21527fe989ed59c1541ae3c17803a952bf704f92
  hash-bionicgpt-rag-engine: sha256:a4057199e0bd628fe23f165f066a27e749b356c150ffd7d267f64f95e5bfd570
  hash-bionicgpt-db-migrations: sha256:e3065874421bfb0e3a23164eee24f6f878f001d79b8b098de8607c0eae69d6e6