apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.27
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:ce1c68ae48e34a1f2e27e23eb9a2be9b34e28c890524f3720e348503c37f4bcb
  hash-bionicgpt-rag-engine: sha256:cc163238b8c0bff3daa1e80dd3a3408a003c5788d79b51d4610519de6ea1f9ff
  hash-bionicgpt-db-migrations: sha256:192648a56fc21ced6c1dc1409a067b5a3f7985a230fd30b123cb8647d316a3f0