apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.51
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:66ef3eaccc1840c774936034a4f0453baf214290377ae646662d69d6942b81fa
  hash-bionicgpt-rag-engine: sha256:6064248a45f617aee91bf13a3cc9b7795e2d681c76985dfb08b3ed1642cd7b81
  hash-bionicgpt-db-migrations: sha256:ba859a5a373bc4f8c37ecdbac972f16451311e60a7f58de3b9bba3d735c538fa