apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.43
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:54e278511af078bb8ed11a428aaf0ca9061ac0ef05e682a99ed51814bd3c038f
  hash-bionicgpt-rag-engine: sha256:b009acf11bcd48c6bd40e3a559729176c39c5fdc554a3c6908395eca19b83c15
  hash-bionicgpt-db-migrations: sha256:dea49d1dbc299e60308a1c778ebc7b7cc51e42bef901056768971b9b2f6ffb86