apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.36
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:9a77b07b2e8439616c007f24c18be33e32192fb9ddf25a3f4edf9781cb37193d
  hash-bionicgpt-rag-engine: sha256:8f2be4f9a4f0f14d370d5c1a1cc8eb6eaae792bf4680014f5d9353c2a8df66a8
  hash-bionicgpt-db-migrations: sha256:da44b157c0665dc7e49c658866c6809444468d1d8d24780f8b9683290adc544c