apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.26
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:ec625b4092d1ad454fb0155a959116654a591e4a0ec9dc83d5872b2745d0f403
  hash-bionicgpt-rag-engine: sha256:6dadc1877c2000a9dfc19cd26f22b52bd8dce88342353d8df2d1284ef4714461
  hash-bionicgpt-db-migrations: sha256:9731b77a25ce384d677a955137c923699ce51073be542fe6c4837c1f6ff86131