apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.33
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:e61ec1d165bede30afe45594ddb7e3ae6e2793245d0d50a70e267d2afc3a5b13
  hash-bionicgpt-rag-engine: sha256:a7f5beb59d1676694ff780d22741a552d677e5a6521a118107afed228ff69338
  hash-bionicgpt-db-migrations: sha256:3ebd002c1f1910bb49f65e769ae23e1446e53ad91af3323411b26620746fe988