apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.13
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:34aa5bc9371c5f172db958d4fd9443777fb46b288925903e58f9088210c4e554
  hash-bionicgpt-rag-engine: sha256:4615f89657e21b6c7f8d8fad229d6672b9ada9a1058ffbd97f86874ed9d6b3c2
  hash-bionicgpt-db-migrations: sha256:285820373a311393deaab88ebf18a2df2ff6105ba49a565ca2e9dae09ada3d40