apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.16
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:67243c3970215b5bb6e5afb27d826e4183f43cc924da6feec79af606c82e6dd3
  hash-bionicgpt-rag-engine: sha256:ffe326f8e925e4f59320f1cb71cffecac319a0dc4a8fed22e2cc9a03129e303a
  hash-bionicgpt-db-migrations: sha256:c0aaac3193932428062d8db3ff654b561a2dfd7bda2abeaf1808c079f0ed0d02