apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.4
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:9416b01506dead7a240c11c764821731c3e105ec165746e54d1eaaf27ee12fed
  hash-bionicgpt-rag-engine: sha256:e1ff4b086f371fd79c64218a725ed09053174f9ffd79fcbbf018e58341274973
  hash-bionicgpt-db-migrations: sha256:cebb2942852b4bb212cb10ad2c6b3a582153e7ef7454ef1749701d5c48f5deec