apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.7.34
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:a527fd37af42b3e9f2ee488c01c43250a8bf3c66c73d6f4fc120c4119b800a85
  hash-bionicgpt-pipeline-job: sha256:2ab1a88f6871d5d302bc9abe12aebc3cbcd4959e14329d2ffb4419db03396d8b
  hash-bionicgpt-db-migrations: sha256:354a6c5563af2e8530b84dda080418caf08eea818352092eecdf7c0471c03f9d