apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.8.20
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:30caacccc35f716c9cbd5aea3ca3d26b9ab3f26b22d8d6f6130e75c3d1ca2472
  hash-bionicgpt-pipeline-job: sha256:5ed0d7a22aba67631b6e583146f25ab6beaaa33f5c863969c5157085aefb0fcb
  hash-bionicgpt-db-migrations: sha256:3b4d6177948c4eb54d9e4e24932e704aa38bf8a8c68ad76c5b04c8d0931dad75