apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.11.0
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:9eedb8075225bc97c263ad3434cda5b79ab9af4ed3c067fdff98f924e1324a41
  hash-bionicgpt-rag-engine: sha256:01b4987bc389bef0c97d7c10ae2ca2c4821449abeb62beb41095420df3be7b16
  hash-bionicgpt-db-migrations: sha256:70b645a9a263b71bec08838fc7ec23a083d805b932224857af3b0c3234938fbd