apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.8.31
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:cc5d1e5cd0563b004cfaf0dcbc75be3b0e2af30961a04f51044c884c2d9d7dc1
  hash-bionicgpt-rag-engine: sha256:6bae8284ce0eddc66db3531702ccd7b76bfdb313b37216c27bcf735b8ef626ec
  hash-bionicgpt-db-migrations: sha256:e8828ce4795317bc90c67ac9e163faa484a3ff21875435ff6ff4acf4d53cd1d4