apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.11
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:1c3177daa8b100e39f0b8ae43227ffd5b0e28c18f20da9981cf5c1748e5038e0
  hash-bionicgpt-rag-engine: sha256:84cf316c762c9b6fa679bb12c4a5673911077894f0278adf78445d3017edf01b
  hash-bionicgpt-db-migrations: sha256:286ceabf20df8a3130b8bb7435d3a23a2f53ca72d164cfad8127376d6951c57e