apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.30
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:794c941bd6dab718dad5cd1fb8f03c15c2e076151cc9d6f1b9673d5dbeee93ff
  hash-bionicgpt-rag-engine: sha256:de263509d2e2b15790a4c5a4b369b9044101fd4dcf39ae7fff05030e19219846
  hash-bionicgpt-db-migrations: sha256:185ee39a94bed977353a49178d50ecc4feec21d0f7d85d97b79ab3bdea7eb1d1