apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.53
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:1a93358a8b465d1ada35fe50e31b076ab8183d9d8bc33b308ae263519246f17f
  hash-bionicgpt-rag-engine: sha256:7ee3156e058b79f894702579465edee48c5c35657c30b036bb8cf5835d41ce0d
  hash-bionicgpt-db-migrations: sha256:6e3acd656fefa2a093b4edf89d649c4657e2847793b17c1b9c2f9b7667b5c340