apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.7.46
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:466b8d228aaecd2e3f6e01ca1b9a6804690cf222cc212316ffd6648bf6f90945
  hash-bionicgpt-pipeline-job: sha256:5d4f9935b5ff62acdf889670d02364786a5689adaf721d655069210624336922
  hash-bionicgpt-db-migrations: sha256:0055f315c93e61569c86403d3979f5ecb7c9106fbf9be9411685880edb2e1d3b