apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.3
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:017693e928b859ab36cee9b2f9b2bfdad1f5a821cddbdd5db3425f40f16d51d8
  hash-bionicgpt-rag-engine: sha256:eb5141e6f1ce61ad51cf68248c0a86c385a0deb85fda32cd9f34dcf8df2fcd1b
  hash-bionicgpt-db-migrations: sha256:550ddd2411ed1d0c290e6ade0611b1643f68b047f0d23dd774014789724ae675