apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.41
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:79bd68b8317049700f3712b21db429de59c106986fa4edf4fc058a4e0fda78ec
  hash-bionicgpt-rag-engine: sha256:b32a07080baa2f6349d40e618159d736ae14a175a39c4d4ae6d351637f679035
  hash-bionicgpt-db-migrations: sha256:c491522404ebef23be4726139548a4dfd56461b02b5cf2bb9afcdc2cc347124f