apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.8.30
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:5b172fbc312382f872d91cd50f450e69da29692419ebc64fa03e66989e15a749
  hash-bionicgpt-rag-engine: sha256:035ca179aaa821f3dbb902b2f4c9439f310a7554847b3e4228d004e950dbfb47
  hash-bionicgpt-db-migrations: sha256:c7e59b9bea1e88bc82ef67b99a39b9453e245340dbdf5f84afdc7bef6608e990