apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.35
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:d52ab0968d20ad72336162a26fa8ec5a9813669095ef8b706d0ff9559ffbc656
  hash-bionicgpt-rag-engine: sha256:29fe03b63e395d15bf9b593708136178b0360ca8d63d738de56bf27e52af4deb
  hash-bionicgpt-db-migrations: sha256:74c5b27e1dfe3cda87e4c508c047076bdce29851aaedfdedb99b8003642b7ae9