apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.8.21
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:8ce6134f50d329deb053bfa286c1fdd6bce3e8298cfdbe313009793d567e2da0
  hash-bionicgpt-rag-engine: sha256:4e043b1fd0128246150250fbb27cea065cf419b1ae134095fc36bc9d80e17f37
  hash-bionicgpt-db-migrations: sha256:4fd67bf2aeaf1feace81b7fc4d8a83177eba4f68b39f875c7443f6a001798659