apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.7.43
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:70612c381e90e73503e1cee53564641689e288a643cba1f6b85f0e4b1cc08063
  hash-bionicgpt-pipeline-job: sha256:fa640c3ff9695556d81131335b1e77e8bea4fce0382f62dbc283761a2bdabaf1
  hash-bionicgpt-db-migrations: sha256:116b08fbf24eda77c1cf41d21c2dc58f8960cd196470dea6fc5c0f8ec1a36f42