apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.47
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:cfb6e7da291deacaeab55fe4605fe38e747cc6acb127fc1a677f870c2ba1056b
  hash-bionicgpt-rag-engine: sha256:b128d4c4203e6c998467b36e5f6e8ed56108428056230284bce0bd12b0dae140
  hash-bionicgpt-db-migrations: sha256:87d31bbb7b75624f8bdc32c81c99d1b489eadadd758864d4082e6e15a6e87141