apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.10
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:502a47dccf63c5c6b05e465abe606d1332d626a0cef527b3bcb908ff55866157
  hash-bionicgpt-rag-engine: sha256:c83eb8a5a84ab68f49af0d92a77bf08031b838dc80b90b74f1abed7788262762
  hash-bionicgpt-db-migrations: sha256:6f4fcc53afdea4d165a5717972a8e942537390a95ce93eece0a938ae62815ba7