apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.11.17
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:1ece2795def3b6516d2e1345603942b386c2912c89e584e26d86c654a6f546d7
  hash-bionicgpt-rag-engine: sha256:74369e82e322fb88d342de208202976ee23a06ef4e09889fe6af485075f8d6f4
  hash-bionicgpt-db-migrations: sha256:a9b2cc3986733297af66bc5fbced920568220e3e095834560fee70726840a018