apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.10
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:f368b52cb98a0db61b6c9979cb8ead88f691e0907e3aa686b7f5b756f1feafe8
  hash-bionicgpt-rag-engine: sha256:3014fe0a15c2baa021a9dc86cfda938e2e883759e5ac2d4e5659345b1d463d43
  hash-bionicgpt-db-migrations: sha256:909096cfa7f57860a6cce8f8a96d5322e493a034e908b8bf51515f47ad0b8415