apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.46
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:7faf02d387ea0dd8e839cb34a8a45dde12ffd1c2e402c51b73e94c5309682a84
  hash-bionicgpt-rag-engine: sha256:852aad1add8c717b2cbde9c35eb894d1db71740fc6f5c69ed5c511a4e06cde47
  hash-bionicgpt-db-migrations: sha256:c9ec15e8e5ebbb461f8f6af43092b56e66dee33336cb12d84ac5e9933cd21047