apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.7.41
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:7c41d15fcf74bfdae091db50dc6513a3b7ea58b6a8362bd01023761f67a68260
  hash-bionicgpt-pipeline-job: sha256:6e52e28454756c0ab74abbf74495480b795ca813d4a395d386d6fa17fb477fe5
  hash-bionicgpt-db-migrations: sha256:93efa531a2e5b5d9deee221fe9f73f8a25d22c921364f71df3c6950f45528549