apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.8
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:1e79acf677e081899ea508b46093f1d758457041a7c2b41fd02068f2f2af55ae
  hash-bionicgpt-rag-engine: sha256:99892486fe90fb06c4ce8679957c74f3592616ad0a417c0e6bba26e7341cc4a9
  hash-bionicgpt-db-migrations: sha256:54feb794504e5829cf4a5f83b7498536da47198b2b6432e91319a0b81d0e3c2f