apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.26
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:44b5d7e0e74d9d84a342d17f1acd20db3511e525654617e5fc0f74904ee5aeba
  hash-bionicgpt-rag-engine: sha256:c387aa36aeb3ffaf71254404abf72e7616d593ce572ffabc2a0fc9ec0a70efea
  hash-bionicgpt-db-migrations: sha256:7bf469561af09ddd723ba6416f31a156bf41350c19c9cc03b3a3994354aa8e94