apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.16
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:daecacf8a5fd014b025986a1d153ee1cdba8bbf431353c5aab451194ef088fcf
  hash-bionicgpt-rag-engine: sha256:6ba3d01c4e9faef6bb4cf151b5767bf569558264d5a11725b15516c6c74dd63e
  hash-bionicgpt-db-migrations: sha256:6d5196c3360357ee36c6d1fdf37026839f1a8d2c3ce956b8cbe0a6a3d5925aa9