apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.28
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:e212b351a4acdba79111ba0f602361df0e72d5c7068b9f0e4b1ae6906e1515ff
  hash-bionicgpt-rag-engine: sha256:096bbfcc2f0da78b4bb285d9c573c8c9c6fe04bb060c60c9feddf041fe9769fe
  hash-bionicgpt-db-migrations: sha256:b4f1abf3dd993345721a51f7d0cb4ba17233db6e5235254378793319a447fad7