apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.21
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:9a036da7b18408f144a3c70e0379fe60aaa3e2a72acde1e77380d26d0903b5f9
  hash-bionicgpt-rag-engine: sha256:8b266570f5964baf63cd7cc3d0b321a5c47b4db3ed4afbef51291788e67dddfa
  hash-bionicgpt-db-migrations: sha256:8d07f6589d7489eb59a6fd51c9c11546728d933aeb783c4584c381e70d9f1a29