apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.11.21
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:891e6a860bdf6788c0653fb9c69b725132c8c942f413e996de0dfbe4da54028e
  hash-bionicgpt-rag-engine: sha256:6a03eeb5d25351a6cc821c0153507119cf2b08bebd05cbaa1bebd00d38fbee97
  hash-bionicgpt-db-migrations: sha256:80ca955604b37133870037582531f34b920d68d025ccf9debef7f1d595b4b45b