apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.28
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:7027a1c783930ce1f5e9f47c7a55922679d0a299e72fb12bdc20f138a7554342
  hash-bionicgpt-rag-engine: sha256:36b584799bed8c137ae37949530649badb197d1fc8ef7b622a1a0bf21d65043a
  hash-bionicgpt-db-migrations: sha256:fa28cbf9b4e7b48617220d035557894adf6f83581527685efc0d529a6904d337