apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.8.17
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:b6bc9a60d0253a5ecc672d2971f763c52a8352cc8b1fdce6395ffb00fdb283a8
  hash-bionicgpt-pipeline-job: sha256:8c4aa245911707f08be91412ee0f569f220e4d2bf3c2b4b5e54e2f3687224759
  hash-bionicgpt-db-migrations: sha256:541525c78dcc3db3369f0aaf04393edf3b2731b21d1c03f1be3ca3c31f06b4a9