apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.13
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:12da6478bac21374ac6e3079b342a0b3781a3581e77ff0e37eb21b5c66f31b39
  hash-bionicgpt-rag-engine: sha256:83c61b282313813f0b6888f2d256a86a4bddc6a118072ecb16e168c125d8c9e7
  hash-bionicgpt-db-migrations: sha256:b4f1f678e4eb05f8d3629a9ce9acda683c4656f4d41ce4646a03b0a074c49f6a