apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.1
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:7225e0c548fe5d9ff8775bd524d0105a5c1733bd83f9848c34a69108beb8f741
  hash-bionicgpt-rag-engine: sha256:a3e0d96416f278b1ebba3127b32ca9d96f625459143c40d88baf5046fd622d2f
  hash-bionicgpt-db-migrations: sha256:7f0bda0684faafe95ae45fffb3b69824339d219b53d3c95db73a94ba4b1019a3