apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.19
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:97a89b991654630c8bbf452111fa8acedbb6639243d40f16d2c1316a41c2b7f7
  hash-bionicgpt-rag-engine: sha256:a8f4d4ef68b6a57b65ee796695d82b79809bf454fe6a702a0d3b64f7b2eaaaa6
  hash-bionicgpt-db-migrations: sha256:4f5f99e329dc8084d409c19132b8118465b5bb591d85be7d97a2c0414cefc8a6