apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.40
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:d073fa5d2dfd2d41893e4037dc4102212285055b7a6c70ae5223709e888552c7
  hash-bionicgpt-rag-engine: sha256:075501339fb0e892d52d9faf719c7cafdbe22a88b00afcc01baf7db94013c359
  hash-bionicgpt-db-migrations: sha256:de74b46ca3d37ca22de21e2956addd220a90e6dff29a5093d7ea626fb868592c