apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.60
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:d3a831628e2f9c343b6ccbe4fd5c700501aff81ab4c9a45fd4e76a2b11be9cce
  hash-bionicgpt-rag-engine: sha256:4f2080a69ff618cfdb4d1689d36c186105d3b145ea3c63f545ad069f8f7665c4
  hash-bionicgpt-db-migrations: sha256:4cb485eb1dcd5066a92d67d865eb449714e829f32220695b8e65178b1ef51f3f