apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.32
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:4829c20807c806f15d1964d3bb0714568bcf7089e7ff8ebbe5979caf7a254d7e
  hash-bionicgpt-rag-engine: sha256:08e753f275c6dc110a055fd6569740e037fc634a6987630594d61ce9771ff9d8
  hash-bionicgpt-db-migrations: sha256:726e6e328f55ef84cd0b5882cc37bfcabd5186ce3cef5655266f2ae703651563