apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.7.45
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:0de681e4b8c90e72c4b09f150c103cdba09876178396caf4ac1a2b7e704a40d6
  hash-bionicgpt-pipeline-job: sha256:2ad807358371302006e9feb511ba86778176b06a28005a1dc2aba5bfa8d4f446
  hash-bionicgpt-db-migrations: sha256:1d3d81431b18a171f5376f001f3a060ac62bd1cd7410ee2adc73476d7d88cfa1