apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.11.13
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:bd86310cb0422a01765b7873c292017eb0bf931cbdbb4bcd24d1df7969ca633f
  hash-bionicgpt-rag-engine: sha256:ea839466b9ea3fc44b8d48cbb20123959d5184d93178d7961d4ce0902a25d211
  hash-bionicgpt-db-migrations: sha256:0a06867b6dc6fce75b1ea871f54c65ec36593164967deb238b10af3fc27853b1