apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.8.36
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:2ceb22b2941c4931dd549fabdb926c4fe18020cd8cf8222f1257ac7037a30069
  hash-bionicgpt-rag-engine: sha256:e14ec9558744c9ac3e0da48b896191870cc5774d5b717207bf0715ebdc359ac8
  hash-bionicgpt-db-migrations: sha256:e611e685eaa74da214044746d0bbabffb986c84c041f178ec8ca254c77d55d53