apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.11.11
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:e8ebd8fe44169b34266ea3ea82d80645c9db8ba9a5e711881725cd4eb2e84d71
  hash-bionicgpt-rag-engine: sha256:a9eb9695efc9d69a281cb1b8f9464d4afcfb613f59fcf32ab85e658b25a4e23a
  hash-bionicgpt-db-migrations: sha256:13ab645d40466059c39eff85db7dafdab1c74499e4d87ce36707764e78b67344