apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.2
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:3240a1e927eea0211a8f2b111f01e8b5c478bad1a28f90ba07a4e21f45198d57
  hash-bionicgpt-rag-engine: sha256:00a1050c5240491a8af6cb139c7bb49e8a0cd756cb18417139a2d1d0cf49f6bf
  hash-bionicgpt-db-migrations: sha256:bd6d18f4589767af9cb171868ec1cb60ac2bce2c7cfade83d7d045f9ff6ce277