apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.8.33
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:601d5944e5a49a94efa8ec481130052396f73c3e409f251ede06f3ce54a5f3d0
  hash-bionicgpt-rag-engine: sha256:fd05ca0b3c3fe1807d996e531e256cd5b8aba8155339ac8dfe9eb857e5c8f796
  hash-bionicgpt-db-migrations: sha256:817c9e3b4ad34cdfef967c6e8b375da92b37be64206acc654c630ffaf2d29115