apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.40
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:9aed2b15a1c25296b1b6de569488aa8088ca4ea7daceb28db978a8d2ffd39f4f
  hash-bionicgpt-rag-engine: sha256:3dd4eb88008cce502ac32416f0e3e58b57e863a4e620c2a1f75bd4e9bbf3399c
  hash-bionicgpt-db-migrations: sha256:f7599e995307b52c2196dbfd13d50d15b16e8e36e31c594510e25dbf0cbb728a