apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.8.26
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:b9c4f25467b065fc94a9b6bd0f76fb46035bcbc25315d1fa3ff7ae803d1150cb
  hash-bionicgpt-rag-engine: sha256:30e98aae61549f2f6cfec866caea893e96ef724b4f6fbe999bfcb00c2f0a4fdd
  hash-bionicgpt-db-migrations: sha256:8839609efe0983c22db192fa47cd2cc1b65795919da5829aeef6a419405d48b4