apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.23
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:19ae040e0b5a90058d3f88fe82d74388faf663c406ae2ccdf17553794e056f46
  hash-bionicgpt-rag-engine: sha256:5d1b3185c63cb8cd5dbed1fbfb33748930882c21de7af6c0aa06d6a704f392c7
  hash-bionicgpt-db-migrations: sha256:3482bcba242cf734d522e9931adff69df8f523bb962da9b251e6a9de9df63ca5