apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.27
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:382abb769e62abfc3f080be5e28a854aa12997e60d3a3773e5bb081e0863d861
  hash-bionicgpt-rag-engine: sha256:f6ef8764c030359110ebb4674e15b40570cec76a3ea70777293aa3e1d705f516
  hash-bionicgpt-db-migrations: sha256:9e4a6041eb9167749f4e5489f5671d968c05c5f5fd55aea1fe97a011823952d9