apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.8.10
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:3fd8a2c1695a2bb7c9cb7f18e9d6a8ca3da3f94bc83a65c7e41bf73c2a927026
  hash-bionicgpt-pipeline-job: sha256:e1d302115ec0f6f5b5499953eac0eeabba9feacebce189d7327b19c14ec5f645
  hash-bionicgpt-db-migrations: sha256:1946d2ca6c76f0935360c3f43a97b0a2f9a1ab448ff1e2c486df9b8163f13c95