apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.20
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:be6df15352e668eee0377095db83f4a3db9aceddeb93a0c88621761cf681fbd4
  hash-bionicgpt-rag-engine: sha256:b60008c3d92e0af5a3bcac19b6e90fd7e1c244c4951dcd2daf4ef29143a0b091
  hash-bionicgpt-db-migrations: sha256:30dbb3f7769bed0759afecb2e1cf99855049343016900e86fe370e2237fa99e5