apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.17
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:489058f0a9a0b03f5f44d65c52e76e59e7111460ce9768b5d9a18da0497b23fa
  hash-bionicgpt-rag-engine: sha256:2d35474d1e62a042755ceaafeb606ee374d68e9d36c720d54cb05140db5b70b3
  hash-bionicgpt-db-migrations: sha256:65d66330094f04da8afb0d2142fecfd73d11bbb994f601047b81839185bcac32