apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.11.2
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:0e915637f3edb6b17dbe2e15ca608e012ee0d63d623de76b0158a17a83e16cd0
  hash-bionicgpt-rag-engine: sha256:2f14e409dcc0f3c8a13d6a8c97b68c1bce83c4411b7e81e81c0cc17a60d0608b
  hash-bionicgpt-db-migrations: sha256:0996ff065b170c4ca60c2337e82064d9db951cc8b695efa8ec5c1940e132452c