apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.7.42
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:b8993e5e31cc9886bb7f98c18557bd5c9a4b2a07db8d3ef53294fa6748454b83
  hash-bionicgpt-pipeline-job: sha256:2be38124dbb9da6c5b9f0b9896f4fc3d0a8b2570829bceb5c5036d8e03d8ce01
  hash-bionicgpt-db-migrations: sha256:b451394e1f6394489d773b9a52d5f969fadc0510c08bc17d646889fb353f4b77