apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.36
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:6ac55eba47130059ecf4dab79623510e3a74a2e8aa05796e0ef42f9ed87477c1
  hash-bionicgpt-rag-engine: sha256:9cff9e4ed638a1d32f47ab5c33167e37c0f585dbc06f140ebc482f3f8bc69212
  hash-bionicgpt-db-migrations: sha256:1f4c2fc8ce8f2077f26433b32876f18f39150eb6bd50b611874bb8557ffb9c64