apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.29
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:ac9061cf96ec1d094ab0c4ad1fb3619e668cecabe545ed84a97f6903ac0831c8
  hash-bionicgpt-rag-engine: sha256:e27f10f66526e8a8c01285358389b9c51687603ef8d0ef836d9202e6271c72b7
  hash-bionicgpt-db-migrations: sha256:ef3184a30b5cf97b94f651b558544c529d7e6673ce3c9bfc56ffc76f3b154212