apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.52
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:d5a6916d37391deb4cdf2a83ab61659daede200e1243d22906aff51adee4a42f
  hash-bionicgpt-rag-engine: sha256:2301d334f308511aecb4cefdd187146b27e746d079771a26c122da9d8949ae7f
  hash-bionicgpt-db-migrations: sha256:fdbddd9af1c491a438290091ffbd1a9ba0ad5076b78bcfd8d20d7c4605da0d34