apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.7.32
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:d911c98350e033ab1a09f1834d706e8b209a7875f55d58bc56db9ec2771aa3eb
  hash-bionicgpt-pipeline-job: sha256:6fa05701a870a0f80e0dba0c4495c9a9a24873e702e57a9f9dd8ecd24de964a6
  hash-bionicgpt-db-migrations: sha256:fe43a2749e8d9d3af2692a010ba4c0f71bb5e5aae5010901e8ce7245d2ecb56d