apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.25
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:d626d03ee83bb9f830e6910ca8c9f61a4270948328f1348d5364ed15214e9ab2
  hash-bionicgpt-rag-engine: sha256:cbc93453a40d39739194869b63ec4aba575ad2a9324d62e4109179a22203139b
  hash-bionicgpt-db-migrations: sha256:c6b83ba48e616c09beb327dc396610cdbf07139a758f140dfb2b74c2d971dd80