apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.23
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:1a852ae034b7ee3af23bb88dffff8e4f32ae421982c5e35b882de974497f695d
  hash-bionicgpt-rag-engine: sha256:db52064e1c288ee039d1fe69212dfeb2e6d16a4b435584f526217909587540e5
  hash-bionicgpt-db-migrations: sha256:769ab9b36435e74cb4246e66e84d3e93d98edb66c9ce95fd8695a90d4f0732b7