apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.11.8
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:b4dc13ba2e04e48b56d75cc0930a06fe52b647b57a509903cc058821dda95b60
  hash-bionicgpt-rag-engine: sha256:0beeefcb4efa9eee338abebac2ab36f7eeac17233d3d641c535cc623ac6e1c3f
  hash-bionicgpt-db-migrations: sha256:6a1abfaebaa3ce12c1f61fcf2557173820613a671ce304a44512ed7d2f1a6444