apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.3
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:ec367dd33d911b89a3518c39fc3a79798998311b505aef921792d9db6af016ab
  hash-bionicgpt-rag-engine: sha256:1627f558409138595e998bb4ad0dbd82d5e12b1ae75c55b290bb3122e6ce65d7
  hash-bionicgpt-db-migrations: sha256:264f55523d9cc847e14accd81c098fda86ba08cb58255ba518696a9f87193289