apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.9.12
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:e118c3ccb3ed493384d0918128d0e8f4545775843379824d35811401f87aeaa6
  hash-bionicgpt-rag-engine: sha256:6a21027af54d70fa6e7f0ad439a5279330528f1b114c7cae28e76d08ef8b248a
  hash-bionicgpt-db-migrations: sha256:e36b80d1c40caaa75afdfffd49410bfc62ffd783bb83b3282f7953b5333d7fb7