apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.10.57
  
  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # TGI GPU inference engine
  # gpu: true
  # Testing mode
  # testing: true

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:7837618dc0e2d4f11efd92eac14aea034c9f332ce4f597ea1ea02b1212155816
  hash-bionicgpt-rag-engine: sha256:615155984202a9bbc6f82c7fb10e48ea14c0e643414fd9b37ef29cd01d933d51
  hash-bionicgpt-db-migrations: sha256:966594521a1bc03effed1a52b7d119b661576b9066d560c87e51ad412e5a0b54