name: Debug Auto-Fix Workflow

on:
  workflow_dispatch:

jobs:
  debug-job:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Event Payload
        run: echo "${{ toJson(github.event) }}"
      - name: Debug Environment Variables
        run: env
